import type { Metadata } from "next";
import Link from "next/link";

import PageHeader from "../../components/ui/PageHeader";
import { SITE } from "../../lib/site";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How HireWiz collects, uses, shares, retains, and helps you control personal data.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPolicy() {
  return (
    <main className="flex min-h-screen flex-col items-center pb-20">
      <PageHeader
        badge="Legal"
        title="Privacy Policy"
        subtitle="How personal data is processed when you use HireWiz."
      />
      <div className="w-full max-w-4xl mx-auto px-6 md:px-8 mt-12 text-slate-300 space-y-8 leading-relaxed">
        <p className="text-sm text-slate-400">
          Effective: {SITE.policyEffectiveDate} · Last updated: {SITE.policyEffectiveDate} · Version {SITE.policyVersion}.
          HireWiz is operated by {SITE.operatorName}, trading as HireWiz, in Gujarat, India. For privacy requests,
          email <a href={`mailto:${SITE.supportEmail}`} className="text-primary hover:underline">{SITE.supportEmail}</a>.
        </p>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">1. Scope and our role</h2>
          <p>
            This Policy applies to the HireWiz website and self-service software. HireWiz determines why and how the
            personal data described below is processed for this service. Third-party websites and services have their
            own privacy terms.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">2. Data we process</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong>Account and authentication:</strong> email address, password hash (not your raw password), sign-in method, Google account name/email when you choose Google sign-in, and the time/version of required Terms, Privacy, and age confirmations.</li>
            <li><strong>Profile:</strong> name, headline, phone, location, professional links, target-role preferences, experience, biography, skills, education, and certifications that you choose to add.</li>
            <li><strong>Resume and job-description content:</strong> uploaded filename and extracted text, resume sections and contact details, job descriptions, target role/company text, and information derived from that content.</li>
            <li><strong>Generated results:</strong> compatibility estimates, identified skills and gaps, summaries, learning suggestions, tailored drafts, chat prompts and responses supplied in a request, and match history.</li>
            <li><strong>Market-analysis inputs and results:</strong> role, location, country, work-mode and experience filters, requested sample size, data-source result metadata, and generated summaries.</li>
            <li><strong>Account usage and entitlements:</strong> tier, Premium expiry, analysis-unit balance and deductions, feature requests, and account actions.</li>
            <li><strong>Payment and transaction metadata:</strong> product, amount, currency, order/transaction identifiers, status, timestamps, and limited customer or reconciliation data returned by the checkout provider. Payment credentials are not received or stored by HireWiz.</li>
            <li><strong>Technical and security data:</strong> IP address, device/browser and request information, timestamps, authentication/session data, error and security logs, and cookie or local-storage preferences as generated by the service and its infrastructure.</li>
            <li><strong>Support communications:</strong> the message, registered email, transaction ID, and any other information you choose to send when asking for help, a refund, or exercising a privacy right.</li>
          </ul>
          <p className="mt-4">
            Please do not upload government identification, financial credentials, health information, or unrelated
            sensitive data. Upload another person's resume or personal data only when you have authority to do so.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">3. Sources of data</h2>
          <p>
            Most data comes directly from you, your browser, or the files and text you submit. If you choose Google
            sign-in, account information comes from Google. Payment status and transaction metadata come from the
            hosted checkout provider. Market-posting data comes from the job-data provider used for your request.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">4. Why we use data</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>create and authenticate accounts, maintain sessions, and provide requested features;</li>
            <li>parse resumes, compare text, generate estimates and suggestions, and keep requested history;</li>
            <li>create orders, confirm payment, deliver paid access, prevent duplicate fulfilment, reconcile transactions, and handle refunds or disputes;</li>
            <li>respond to support, grievance, access, correction, and deletion requests;</li>
            <li>protect users and the service, prevent abuse or fraud, debug failures, and maintain reliability;</li>
            <li>measure aggregate website use only after analytics consent, when analytics is configured; and</li>
            <li>meet legal, tax, accounting, consumer-protection, and regulatory obligations.</li>
          </ul>
          <p className="mt-4">
            Depending on the activity and applicable law, processing is based on your request or agreement to receive
            the service, consent where required, legitimate security and operational needs, or a legal obligation. You
            can withdraw consent for optional analytics through Cookie Preferences.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">5. AI processing and model training</h2>
          <p>
            Resume text, job-description text, prompts, and relevant context are sent to the configured AI API provider
            to produce the feature you request. HireWiz does not use this content to operate a recruitment database or
            make employer decisions. AI providers may process and retain API content according to their applicable
            terms, account settings, and legal obligations. We do not make a blanket promise about a third party's
            training or retention practices beyond the controls actually configured for HireWiz.
          </p>
          <p className="mt-4">
            The current provider roles are described on the{" "}
            <Link href="/subprocessors" className="text-primary hover:underline">Service Providers page</Link>. If
            HireWiz later proposes using customer resume content to train or improve its own model, we will first update
            this Policy and implement any notice, choice, or consent required by law.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">6. When data is shared</h2>
          <p>We do not sell personal data or candidate databases. Data is shared only as needed with:</p>
          <ul className="list-disc pl-6 mt-4 space-y-2">
            <li>cloud hosting, database, and delivery providers that run the website and API;</li>
            <li>AI API providers for requested analysis and generation;</li>
            <li>job-data providers, which receive market-search parameters but are not intended to receive resume content;</li>
            <li>Google for optional Google sign-in and, after consent where configured, analytics;</li>
            <li>the payment processor used for hosted checkout, fraud screening, confirmation, refund, and dispute handling;</li>
            <li>professional advisers, authorities, or counterparties when reasonably necessary to comply with law, protect rights and security, or complete a legitimate business reorganization.</li>
          </ul>
          <p className="mt-4">
            We ask service providers to process data for their defined function. Their independent legal obligations and
            services are also governed by their own terms.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">7. Payments</h2>
          <p>
            Checkout is hosted or securely presented by the payment processor used for your order. Card numbers, CVV,
            UPI PINs, and bank-login credentials are submitted to that provider, not HireWiz. HireWiz receives only the
            transaction and status data needed to match the order, provide access, reconcile, support, refund, and meet
            record-keeping duties. The active processor is identified during checkout after it has been approved and enabled.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">8. Retention and deletion</h2>
          <p>
            Account, profile, resume, job-description, and generated-history data are kept while your account is active
            so the service can provide saved features. When you delete the account, the application deletes associated
            active-database records. Some information may remain temporarily in infrastructure backups or with service
            providers until their ordinary overwrite/deletion cycle completes.
          </p>
          <p className="mt-4">
            Transaction, fraud, dispute, tax, accounting, and legal records may be retained for the period required by
            applicable law or to establish and defend legal claims. Security logs and support communications are kept
            only as long as reasonably needed for the purpose for which they were collected. Exact infrastructure and
            provider retention periods can vary by record and legal requirement.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">9. Your choices and rights</h2>
          <p>
            Subject to applicable law, you may request access, correction, or deletion; withdraw consent where
            processing relies on consent; and raise a complaint. Profile data can be corrected in your account. Account
            deletion is available in Profile or by verified email request. We may ask for information needed to verify
            identity and protect the account before completing a request.
          </p>
          <p className="mt-4">
            Use the footer's Cookie Preferences control to reject or withdraw optional analytics consent. You can also
            use browser controls, although blocking essential authentication storage may prevent sign-in.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">10. Security</h2>
          <p>
            We use technical and organizational safeguards appropriate to the service, including access controls,
            password hashing, encrypted HTTPS transport, and restricted application access to account data. No online
            service is risk-free, and this statement is not a claim of an external security certification.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">11. International processing</h2>
          <p>
            Some service providers operate infrastructure outside India or across multiple regions. Data may therefore
            be processed in other countries, where legal protections may differ. We use provider and contractual
            arrangements available to us and will apply transfer safeguards required by applicable law.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">12. Age limit</h2>
          <p>
            HireWiz is intended for people aged 18 or older. We do not knowingly offer accounts to children. If you
            believe a minor created an account, contact us so the report can be reviewed.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">13. Incidents and policy changes</h2>
          <p>
            If a personal-data incident requires notification under applicable law, we will notify affected people and
            authorities as required. We may update this Policy for product, provider, or legal changes. The date and
            version above will change, and material changes will receive additional notice where appropriate.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">14. Contact and grievance</h2>
          <p>
            Send privacy requests or complaints to{" "}
            <a href={`mailto:${SITE.supportEmail}`} className="text-primary hover:underline">{SITE.supportEmail}</a> or
            contact {SITE.grievanceContactName}, {SITE.grievanceContactRole}, using the details on our{" "}
            <Link href="/contact" className="text-primary hover:underline">Contact page</Link>.
          </p>
        </section>
      </div>
    </main>
  );
}
