import PageHeader from "../../components/ui/PageHeader";

export default function TermsOfService() {
  return (
    <main className="flex min-h-screen flex-col items-center pb-20">
      <PageHeader 
        badge="Legal"
        title="Terms of Service" 
        subtitle="The rules and guidelines for using HireWiz." 
      />
      <div className="w-full max-w-4xl mx-auto px-6 md:px-8 mt-12 text-slate-300 space-y-8 leading-relaxed">
        <section>
          <h2 className="text-2xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
          <p>
            By accessing or using HireWiz, you agree to be bound by these Terms of Service. If you do not agree, you may not use the platform.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">2. Description of Service</h2>
          <p>
            HireWiz provides AI-driven career tools, including resume parsing, job matching, and learning strategy generation. The output provided by our AI models is intended for guidance and informational purposes only.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">3. Disclaimers and Limitations</h2>
          <p>
            <strong>No Guarantee of Employment:</strong> While our tools are designed to optimize your resume and improve ATS match rates, we do not guarantee that using our platform will result in interviews, job offers, or career advancement.
          </p>
          <p className="mt-4">
            <strong>AI Hallucinations:</strong> Artificial Intelligence can sometimes produce inaccurate or fabricated information. You are solely responsible for reviewing and verifying the accuracy of any bullet points, skills, or strategies generated by our platform before including them in your professional resume.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">4. Acceptable Use</h2>
          <p>You agree not to use the platform to:</p>
          <ul className="list-disc pl-6 mt-4 space-y-2">
            <li>Upload malicious files, viruses, or corrupted PDFs.</li>
            <li>Generate fraudulent resumes or falsely claim qualifications you do not possess.</li>
            <li>Attempt to reverse-engineer, scrape, or overwhelm our AI parsing infrastructure.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">5. Intellectual Property</h2>
          <p>
            You retain all ownership rights to the content you upload (your resume). HireWiz retains all intellectual property rights to the platform, its code, design, and proprietary algorithms.
          </p>
        </section>
      </div>
    </main>
  );
}
